name: $(date:yyyyMMdd)$(rev:.r)
trigger: none
pr: none
schedules:
- cron: "0 3 * * *"
  displayName: First daily build
  branches:
    include:
    - master
  always: true
- cron: "0 15 * * *"
  displayName: Second daily build
  branches:
    include:
    - master
  always: true

variables:
  PoolName: 'Azure Pipelines'
  VmImage: 'ubuntu-18.04'

stages:
- stage: Get_New_Versions
  dependsOn: []
  jobs:
  - job: Get_Tool_Versions
    pool:
      name: $(PoolName)
      vmImage: $(VmImage)
    steps:
    - template: /azure-pipelines/templates/get-tool-versions-steps.yml

- stage: Trigger_Builds
  dependsOn: Get_New_Versions
  jobs:
  - deployment: Run_Builds
    pool:
      name: $(PoolName)
      vmImage: $(VmImage)
    variables:
      ToolVersions: $[ stageDependencies.Get_New_Versions.Get_Tool_Versions.outputs['Get_versions.TOOL_VERSIONS'] ]
    timeoutInMinutes: 180
    environment: 'Get Available Tools Versions - Publishing Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /azure-pipelines/templates/run-ci-builds-steps.yml
